#!/usr/bin/env python3
"""DPO training for 10 niche domains on top of SFT adapters.

Loads each domain's SFT adapter, then runs DPO training on the preference
pairs generated by generate_dpo_pairs.py. Uses mlx-tune DPOTrainer when
available; falls back to a subprocess-based approach mirroring SFT training.

Usage:
    uv run scripts/train_dpo_niches.py --all --dry-run
    uv run scripts/train_dpo_niches.py --domain kicad-dsl
    uv run scripts/train_dpo_niches.py --all
"""
from __future__ import annotations

# Metal buffer fixes — must be set before any model loading.
# Applied only when mlx is available (Mac Studio M3 Ultra target).
try:
    import mlx.core as mx
    mx.set_memory_limit(460 * 1024**3)   # 460 GB
    mx.set_cache_limit(32 * 1024**3)     # 32 GB — forces buffer recycling
except ModuleNotFoundError:
    pass  # mlx not installed; --help / --dry-run still work

import argparse
import json
import logging
import sys
import time
from pathlib import Path

logging.basicConfig(
    format="%(asctime)s %(levelname)s %(name)s — %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    level=logging.INFO,
)
logger = logging.getLogger("train_dpo_niches")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DPO_DATA = PROJECT_ROOT / "data" / "dpo"
OUTPUTS_DIR = PROJECT_ROOT / "outputs" / "stacks"
MODEL_PATH = PROJECT_ROOT / "models" / "qwen3.5-35b-a3b"
PROGRESS_FILE = PROJECT_ROOT / ".ralph" / "progress.txt"

LORA_TARGETS = ["q_proj", "k_proj", "v_proj", "o_proj"]

# DPO uses a much lower LR than SFT (1e-6 vs 5e-5)
DPO_LR = 1e-6

# domain: (rank, epochs)  — rank mirrors SFT, epochs reduced for DPO
NICHE_DOMAINS: dict[str, tuple[int, int]] = {
    "kicad-dsl":   (16, 1),
    "spice":       (16, 1),
    "emc":         (12, 1),
    "stm32":       (8,  1),
    "embedded":    (12, 1),
    "freecad":     (4,  1),
    "platformio":  (4,  1),
    "power":       (8,  1),
    "dsp":         (8,  1),
    "electronics": (12, 1),
}

DOMAIN_ORDER = list(NICHE_DOMAINS.keys())

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def sft_adapter_path(domain: str) -> Path:
    """Return the SFT adapter directory for a domain."""
    return OUTPUTS_DIR / f"stack-{domain}"


def dpo_adapter_path(domain: str) -> Path:
    """Return the DPO adapter output directory for a domain."""
    return OUTPUTS_DIR / f"stack-{domain}-dpo"


def dpo_adapter_done(domain: str) -> bool:
    """Return True if DPO adapter already exists."""
    adapter = dpo_adapter_path(domain) / "adapters.safetensors"
    return adapter.exists()


def sft_adapter_exists(domain: str) -> bool:
    """Return True if SFT adapter exists (prerequisite)."""
    adapter = sft_adapter_path(domain) / "adapters.safetensors"
    return adapter.exists()


def dpo_data_exists(domain: str) -> bool:
    """Return True if DPO training data exists for this domain."""
    path = DPO_DATA / domain / "train.jsonl"
    return path.exists() and path.stat().st_size > 0


def count_examples(path: Path) -> int:
    """Count JSONL lines."""
    try:
        return sum(1 for _ in path.open())
    except Exception:
        return -1


def log_progress(msg: str) -> None:
    """Append a timestamped line to .ralph/progress.txt."""
    PROGRESS_FILE.parent.mkdir(parents=True, exist_ok=True)
    ts = time.strftime("%Y-%m-%d %H:%M:%S")
    line = f"[{ts}] DPO {msg}\n"
    with PROGRESS_FILE.open("a") as fh:
        fh.write(line)
    logger.info(msg)


# ---------------------------------------------------------------------------
# Dry-run
# ---------------------------------------------------------------------------


def dry_run(domains: list[str]) -> None:
    """Print DPO training plan without loading any model."""
    logger.info("DRY RUN — no model will be loaded")
    header = (
        f"{'Domain':<14} {'rank':>4} {'ep':>3} {'lr':>8}  "
        f"{'sft_adapter':<10} {'dpo_data':<10} {'status'}"
    )
    print(header)
    print("-" * len(header))

    for domain in domains:
        rank, epochs = NICHE_DOMAINS[domain]
        sft_ok = "YES" if sft_adapter_exists(domain) else "MISSING"
        data_ok = "YES" if dpo_data_exists(domain) else "MISSING"

        if dpo_adapter_done(domain):
            status = "DONE (skip)"
        elif sft_ok == "MISSING":
            status = "BLOCKED (no SFT)"
        elif data_ok == "MISSING":
            status = "BLOCKED (no DPO data)"
        else:
            n = count_examples(DPO_DATA / domain / "train.jsonl")
            status = f"PENDING ({n} pairs)"

        print(
            f"{domain:<14} {rank:>4} {epochs:>3} {DPO_LR:>8.0e}  "
            f"{sft_ok:<10} {data_ok:<10} {status}"
        )


# ---------------------------------------------------------------------------
# Training via mlx-tune DPOTrainer (with graceful fallback)
# ---------------------------------------------------------------------------


def _load_dpo_dataset(domain: str) -> list[dict]:
    """Load DPO preference pairs from data/dpo/<domain>/train.jsonl."""
    path = DPO_DATA / domain / "train.jsonl"
    records: list[dict] = []
    with path.open("r", encoding="utf-8") as fh:
        for lineno, raw in enumerate(fh, start=1):
            raw = raw.strip()
            if not raw:
                continue
            try:
                records.append(json.loads(raw))
            except json.JSONDecodeError:
                logger.warning("Bad JSON line %d in %s", lineno, path)
    logger.info("Loaded %d DPO pairs for %s", len(records), domain)
    return records


def _try_mlxtune_dpo(domain: str) -> bool:
    """Attempt DPO training via mlx_tune DPOTrainer. Returns True on success.

    mlx_tune DPOTrainer is still experimental — its API may differ from
    SFTTrainer. We attempt the import and fall through on any error.
    """
    rank, epochs = NICHE_DOMAINS[domain]
    output_dir = dpo_adapter_path(domain)
    sft_dir = sft_adapter_path(domain)

    try:
        from mlx_tune import DPOConfig, DPOTrainer, FastLanguageModel  # type: ignore[import]
    except ImportError:
        logger.warning("mlx_tune.DPOTrainer not available — falling back to subprocess")
        return False
    except Exception as exc:
        logger.warning("mlx_tune import error: %s — falling back", exc)
        return False

    dataset = _load_dpo_dataset(domain)
    if not dataset:
        raise RuntimeError(f"Empty DPO dataset for {domain!r}")

    model_id = str(MODEL_PATH) if MODEL_PATH.exists() else "Qwen/Qwen3.5-35B-A3B"

    try:
        model, tokenizer = FastLanguageModel.from_pretrained(
            model_id,
            max_seq_length=2048,
            dtype=None,
            load_in_4bit=False,
        )

        # Apply SFT adapter first (warm-start for DPO)
        if sft_dir.exists():
            try:
                model.load_weights(str(sft_dir / "adapters.safetensors"), strict=False)
                logger.info("Loaded SFT adapter from %s", sft_dir)
            except Exception as exc:
                logger.warning("Could not load SFT adapter weights: %s", exc)

        model = FastLanguageModel.get_peft_model(
            model,
            r=rank,
            target_modules=LORA_TARGETS,
            lora_alpha=rank * 2,
            lora_dropout=0.0,
            bias="none",
        )

        output_dir.mkdir(parents=True, exist_ok=True)

        trainer = DPOTrainer(
            model=model,
            train_dataset=dataset,
            tokenizer=tokenizer,
            args=DPOConfig(
                learning_rate=DPO_LR,
                num_train_epochs=epochs,
                per_device_train_batch_size=1,
                gradient_accumulation_steps=4,
                output_dir=str(output_dir),
                adapter_path=str(output_dir),
                seed=42,
            ),
        )
        trainer.train()
        return True

    except TypeError as exc:
        # DPOTrainer API might differ — graceful fallback
        logger.warning("DPOTrainer API mismatch (%s) — falling back to subprocess", exc)
        return False
    except Exception as exc:
        logger.error("DPO training via mlx_tune failed: %s", exc, exc_info=True)
        return False


def _subprocess_dpo(domain: str) -> None:
    """Run DPO training via a generated Python script (subprocess, like SFT).

    This mirrors train_niches_mlxtune.py's approach and uses mlx_lm lora
    with the DPO objective flag when available.
    """
    import subprocess
    import yaml

    rank, epochs = NICHE_DOMAINS[domain]
    output_dir = dpo_adapter_path(domain)
    sft_dir = sft_adapter_path(domain)
    data_path = DPO_DATA / domain / "train.jsonl"
    output_dir.mkdir(parents=True, exist_ok=True)

    n_examples = count_examples(data_path)
    iters = max(1, int(n_examples * epochs / 1))  # batch=1

    config: dict = {
        "model": str(MODEL_PATH) if MODEL_PATH.exists() else "Qwen/Qwen3.5-35B-A3B",
        "fine_tune_type": "dpo",
        "lora_parameters": {
            "rank": rank,
            "alpha": rank * 2,
            "dropout": 0.0,
            "scale": 2.0,
            "keys": list(LORA_TARGETS),
        },
        "num_layers": 40,
        "learning_rate": DPO_LR,
        "batch_size": 1,
        "grad_accumulation_steps": 4,
        "iters": iters,
        "max_seq_length": 2048,
        "grad_checkpoint": True,
        "save_every": 50,
        "steps_per_report": 10,
        "steps_per_eval": 100,
        "val_batches": 10,
        "train": True,
        "seed": 42,
    }

    # Include SFT adapter path if it exists
    if sft_dir.exists():
        config["adapter_path"] = str(sft_dir)

    config_path = output_dir / "dpo_config.yaml"
    with config_path.open("w") as fh:
        yaml.dump(config, fh, default_flow_style=False)

    train_script = f'''import mlx.core as mx
mx.set_memory_limit(460 * 1024**3)
mx.set_cache_limit(32 * 1024**3)
import sys
sys.argv = ["mlx_lm", "lora",
            "--config", "{config_path}",
            "--data", "{data_path.parent}",
            "--adapter-path", "{output_dir}"]
from mlx_lm.cli import main
main()
'''

    script_path = output_dir / "_train_dpo.py"
    script_path.write_text(train_script)

    python = Path.home() / "KIKI-Mac_tunner" / ".venv" / "bin" / "python3"

    t0 = time.time()
    result = subprocess.run(
        [str(python), str(script_path)],
        cwd=str(PROJECT_ROOT),
        capture_output=False,
    )
    elapsed = time.time() - t0

    adapter = output_dir / "adapters.safetensors"
    if result.returncode != 0 or not adapter.exists():
        raise RuntimeError(
            f"DPO subprocess training failed (exit {result.returncode}) for {domain!r}"
        )

    logger.info("Subprocess DPO done for %s in %.1f min", domain, elapsed / 60)


def train_domain(domain: str) -> None:
    """Train DPO for one domain: try mlx_tune first, fall back to subprocess."""
    if not sft_adapter_exists(domain):
        raise RuntimeError(
            f"SFT adapter missing for {domain!r} at {sft_adapter_path(domain)}. "
            "Run train_niches_mlxtune.py first."
        )

    if not dpo_data_exists(domain):
        raise RuntimeError(
            f"DPO data missing for {domain!r} at {DPO_DATA / domain / 'train.jsonl'}. "
            "Run generate_dpo_pairs.py first."
        )

    rank, epochs = NICHE_DOMAINS[domain]
    n_pairs = count_examples(DPO_DATA / domain / "train.jsonl")
    log_progress(f"START {domain} r={rank} ep={epochs} lr={DPO_LR:.0e} pairs={n_pairs}")

    t0 = time.time()

    success = _try_mlxtune_dpo(domain)
    if not success:
        logger.info("Using subprocess DPO fallback for %s", domain)
        _subprocess_dpo(domain)

    elapsed = time.time() - t0
    log_progress(f"DONE  {domain} DPO in {elapsed / 60:.1f}min → {dpo_adapter_path(domain)}")


# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------


def run_training(domains: list[str], *, dry_run_mode: bool = False) -> None:
    if dry_run_mode:
        dry_run(domains)
        return

    pending = [d for d in domains if not dpo_adapter_done(d)]
    skipped = [d for d in domains if dpo_adapter_done(d)]

    if skipped:
        logger.info(
            "Skipping %d already-trained domain(s): %s",
            len(skipped), skipped,
        )

    if not pending:
        logger.info("All requested domains already DPO-trained. Nothing to do.")
        return

    results: list[tuple[str, str]] = []

    for domain in pending:
        logger.info("=" * 60)
        logger.info(
            "DPO training: %s (%d/%d)",
            domain, pending.index(domain) + 1, len(pending),
        )
        try:
            train_domain(domain)
            results.append((domain, "OK"))
        except Exception as exc:
            logger.error("FAILED %s: %s", domain, exc, exc_info=True)
            log_progress(f"FAIL  {domain}: {exc}")
            results.append((domain, f"FAILED: {exc}"))

    # Summary
    logger.info("=" * 60)
    logger.info("DPO TRAINING SUMMARY")
    ok = [(d, s) for d, s in results if s == "OK"]
    failed = [(d, s) for d, s in results if s != "OK"]
    for d in skipped:
        print(f"  SKIP     {d}")
    for d, _ in ok:
        print(f"  OK       {d}")
    for d, s in failed:
        print(f"  FAILED   {d}  — {s}")

    log_progress(
        f"DPO SESSION DONE — {len(ok)} trained, {len(failed)} failed, {len(skipped)} skipped"
    )

    if failed:
        sys.exit(1)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="train_dpo_niches",
        description=(
            "DPO training for 10 niche domains on top of SFT adapters. "
            "Requires SFT adapters (train_niches_mlxtune.py) and DPO data "
            "(generate_dpo_pairs.py) to already exist."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=f"Available domains: {', '.join(DOMAIN_ORDER)}",
    )

    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--all",
        action="store_true",
        help="DPO-train all 10 niche domains sequentially.",
    )
    group.add_argument(
        "--domain",
        metavar="NAME",
        help="DPO-train a single domain.",
    )

    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show training plan without loading the model.",
    )
    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    if args.domain:
        if args.domain not in NICHE_DOMAINS:
            parser.error(
                f"Unknown domain {args.domain!r}. "
                f"Valid: {', '.join(DOMAIN_ORDER)}"
            )
        domains = [args.domain]
    else:
        domains = DOMAIN_ORDER

    run_training(domains, dry_run_mode=args.dry_run)


if __name__ == "__main__":
    main()
